apiVersion: v1
kind: Namespace
metadata:
  name: kuryr
  labels:
    name: kuryr
    openshift.io/run-level: "0"
  annotations:
    openshift.io/node-selector: "" #override default node selector
    openshift.io/description: "Kuryr-Kubernetes components"
