apiVersion: v1
kind: Secret
metadata:
  name: kuryr-config-credentials
  namespace: openshift-kuryr
stringData:
  kuryr-credentials.conf: |+
    {{- $AuthInfo := .OpenStackCloud.AuthInfo }}
    [neutron]
    auth_type = {{ default "password" .OpenStackCloud.AuthType }}
    auth_url = {{ $AuthInfo.AuthURL }}
    insecure = {{ .OpenStackInsecureAPI }}
    token = {{ default "\"\"" $AuthInfo.Token }}
    password = {{ default "\"\"" $AuthInfo.Password }}
    username = {{ default "\"\"" $AuthInfo.Username }}
    project_domain_name = {{ default "\"\"" $AuthInfo.ProjectDomainName }}
    project_domain_id = {{ default "\"\"" $AuthInfo.ProjectDomainID }}
    project_id = {{ default "\"\"" $AuthInfo.ProjectID }}
    project_name = {{ default "\"\"" $AuthInfo.ProjectName }}
    user_domain_name = {{ default "\"\"" $AuthInfo.UserDomainName }}
    user_domain_id = {{ default "\"\"" $AuthInfo.UserDomainID }}
    region_name = {{ default "\"\"" .OpenStackCloud.RegionName }}
{{- if .UserCACertificate }}
    # There's no good way to just "append" user-provided certs to system ones,
    # so just configure openstacksdk to use it.
    cafile = /etc/ssl/certs/user-ca-bundle.crt
{{- end }}
