---
apiVersion: v1
kind: Service
metadata:
  name: kuryr-dns-admission-controller
  namespace: openshift-kuryr
  labels:
    app: kuryr-dns-admission-controller
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kuryr-dns-admission-controller-secret
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: kuryr-dns-admission-controller
